"""'initial_migration'

Revision ID: e3e36e92baac
Revises: 
Create Date: 2022-01-18 14:20:39.061449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e36e92baac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_added')
    op.drop_column('todos', 'date_added')
    # ### end Alembic commands ###
